"""update the training model enums

Revision ID: 07d17bff5bf2
Revises: 7f1585d2ebde
Create Date: 2025-05-22 21:28:18.693887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07d17bff5bf2'
down_revision: Union[str, None] = '7f1585d2ebde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM types
old_enum_name = 'storagetype'
new_enum_name = 'modelstoragetype'

old_enum_values = ('WALRUS', 'LOCAL_FS', 'GCS', 'AZURE_BLOB')
new_enum_values = ('WALRUS', 'LOCAL_FS', 'GCS', 'AZURE_BLOB', 'HUGGING_FACE')

# Create new Enum types for SQLAlchemy
old_storage_type_enum = postgresql.ENUM(*old_enum_values, name=old_enum_name)
new_storage_type_enum = postgresql.ENUM(*new_enum_values, name=new_enum_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the new ENUM type
    new_storage_type_enum.create(op.get_bind(), checkfirst=True)

    # Alter the column to use the new ENUM type
    # Note the USING clause to cast existing values to the new type
    # This is important when changing the name of an ENUM or if there are type compatibility issues
    # Here, we are changing the name and adding a value.
    op.alter_column('ai_training_jobs', 'output_model_storage_type',
               existing_type=old_storage_type_enum,
               type_=new_storage_type_enum,
               existing_nullable=True,
               postgresql_using=f'output_model_storage_type::text::{new_enum_name}')

    # Optionally, if the old ENUM 'storagetype' is no longer used by any other column,
    # you can drop it. Be cautious with this step.
    # old_storage_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # If you recreated 'storagetype' in an earlier step or it was never dropped,
    # you might not need to create it again.
    # Ensure old_storage_type_enum is defined or re-create it if necessary.
    # old_storage_type_enum.create(op.get_bind(), checkfirst=True) # Uncomment if 'storagetype' was dropped in upgrade

    # Alter the column back to the old ENUM type
    op.alter_column('ai_training_jobs', 'output_model_storage_type',
               existing_type=new_storage_type_enum,
               type_=old_storage_type_enum,
               existing_nullable=True,
               postgresql_using=f'output_model_storage_type::text::{old_enum_name}')

    # Drop the new ENUM type
    new_storage_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###