"""added a new column on contributions

Revision ID: 25c381f7b652
Revises: 520f11f99c5c
Create Date: 2025-05-21 22:53:36.402782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c381f7b652'
down_revision: Union[str, None] = '520f11f99c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('file_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_contributions_file_type'), 'contributions', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_file_type'), table_name='contributions')
    op.drop_column('contributions', 'file_type')
    # ### end Alembic commands ###
