"""added a new field to ai training job endpoint

Revision ID: 520f11f99c5c
Revises: 6165e8c8c734
Create Date: 2025-05-20 23:13:07.971835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520f11f99c5c'
down_revision: Union[str, None] = '6165e8c8c734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_training_jobs', sa.Column('huggingface_model_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_ai_training_jobs_huggingface_model_url'), 'ai_training_jobs', ['huggingface_model_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_training_jobs_huggingface_model_url'), table_name='ai_training_jobs')
    op.drop_column('ai_training_jobs', 'huggingface_model_url')
    # ### end Alembic commands ###
