"""indexing the data_url field on contributions

Revision ID: 6165e8c8c734
Revises: 0d81d272a6cb
Create Date: 2025-05-20 00:42:15.489697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6165e8c8c734'
down_revision: Union[str, None] = '0d81d272a6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contributions_data_url'), 'contributions', ['data_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_data_url'), table_name='contributions')
    # ### end Alembic commands ###
