"""added on chain id field on preprocessed dataset

Revision ID: 7f1585d2ebde
Revises: fafbd26d4525
Create Date: 2025-05-22 14:26:20.746121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1585d2ebde'
down_revision: Union[str, None] = 'fafbd26d4525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_datasets', sa.Column('onchain_campaign_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_datasets', 'onchain_campaign_id')
    # ### end Alembic commands ###
