"""initial migration

Revision ID: 822d01042dcd
Revises: 
Create Date: 2025-05-19 08:55:33.067541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822d01042dcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('onchain_campaign_id', sa.String(), nullable=True),
    sa.Column('creator_wallet_address', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('data_requirements', sa.String(), nullable=True),
    sa.Column('quality_criteria', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('min_data_count', sa.Integer(), nullable=True),
    sa.Column('max_data_count', sa.Integer(), nullable=True),
    sa.Column('expiration', sa.Integer(), nullable=True),
    sa.Column('metadata_uri', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_activity_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_creator_wallet_address'), 'campaigns', ['creator_wallet_address'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_is_premium'), 'campaigns', ['is_premium'], unique=False)
    op.create_index(op.f('ix_campaigns_onchain_campaign_id'), 'campaigns', ['onchain_campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_title'), 'campaigns', ['title'], unique=False)
    op.create_table('processed_datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('storage_type', sa.Enum('WALRUS', 'LOCAL_FS', 'GCS', 'AZURE_BLOB', name='storagetype'), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('creator_wallet_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_datasets_creator_wallet_address'), 'processed_datasets', ['creator_wallet_address'], unique=False)
    op.create_index(op.f('ix_processed_datasets_name'), 'processed_datasets', ['name'], unique=False)
    op.create_table('user_external_service_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_wallet_address', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('LOCAL_SERVER', 'HUGGING_FACE', 'AWS_SAGEMAKER', 'GOOGLE_VERTEX_AI', 'LIGHTNING_STUDIOS', 'CUSTOM_EXTERNAL', name='trainingplatform'), nullable=False),
    sa.Column('credential_name', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_secret_key', sa.Text(), nullable=True),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_external_service_credentials_platform'), 'user_external_service_credentials', ['platform'], unique=False)
    op.create_index(op.f('ix_user_external_service_credentials_user_wallet_address'), 'user_external_service_credentials', ['user_wallet_address'], unique=False)
    op.create_index('uix_user_platform_credname', 'user_external_service_credentials', ['user_wallet_address', 'platform', 'credential_name'], unique=True)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id_api', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_wallet_address'), 'workflow_definitions', ['wallet_address'], unique=False)
    op.create_index('ix_workflow_definitions_wallet_name', 'workflow_definitions', ['wallet_address', 'name'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_workflow_id_api'), 'workflow_definitions', ['workflow_id_api'], unique=True)
    op.create_table('ai_training_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('user_wallet_address', sa.String(), nullable=False),
    sa.Column('processed_dataset_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('LOCAL_SERVER', 'HUGGING_FACE', 'AWS_SAGEMAKER', 'GOOGLE_VERTEX_AI', 'LIGHTNING_STUDIOS', 'CUSTOM_EXTERNAL', name='trainingplatform'), nullable=False),
    sa.Column('user_credential_id', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('training_script_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING_DATA', 'SUBMITTED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'UPDATING_METRICS', name='jobstatus'), nullable=False),
    sa.Column('external_job_id', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('output_model_storage_type', sa.Enum('WALRUS', 'LOCAL_FS', 'GCS', 'AZURE_BLOB', name='storagetype'), nullable=True),
    sa.Column('output_model_url', sa.String(), nullable=True),
    sa.Column('logs_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['processed_dataset_id'], ['processed_datasets.id'], ),
    sa.ForeignKeyConstraint(['user_credential_id'], ['user_external_service_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_jobs_external_job_id'), 'ai_training_jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_ai_training_jobs_job_name'), 'ai_training_jobs', ['job_name'], unique=False)
    op.create_index(op.f('ix_ai_training_jobs_status'), 'ai_training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_training_jobs_user_wallet_address'), 'ai_training_jobs', ['user_wallet_address'], unique=False)
    op.create_table('contributions',
    sa.Column('contribution_id', sa.String(), nullable=False),
    sa.Column('onchain_contribution_id', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('contributor', sa.String(), nullable=True),
    sa.Column('data_url', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('ai_verification_score', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_index(op.f('ix_contributions_contribution_id'), 'contributions', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_contributions_contributor'), 'contributions', ['contributor'], unique=False)
    op.create_index(op.f('ix_contributions_onchain_contribution_id'), 'contributions', ['onchain_contribution_id'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('contribution_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('activity_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.contribution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_timestamp'), 'activity', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_timestamp'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_contributions_onchain_contribution_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contributor'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contribution_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_ai_training_jobs_user_wallet_address'), table_name='ai_training_jobs')
    op.drop_index(op.f('ix_ai_training_jobs_status'), table_name='ai_training_jobs')
    op.drop_index(op.f('ix_ai_training_jobs_job_name'), table_name='ai_training_jobs')
    op.drop_index(op.f('ix_ai_training_jobs_external_job_id'), table_name='ai_training_jobs')
    op.drop_table('ai_training_jobs')
    op.drop_index(op.f('ix_workflow_definitions_workflow_id_api'), table_name='workflow_definitions')
    op.drop_index('ix_workflow_definitions_wallet_name', table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_wallet_address'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index('uix_user_platform_credname', table_name='user_external_service_credentials')
    op.drop_index(op.f('ix_user_external_service_credentials_user_wallet_address'), table_name='user_external_service_credentials')
    op.drop_index(op.f('ix_user_external_service_credentials_platform'), table_name='user_external_service_credentials')
    op.drop_table('user_external_service_credentials')
    op.drop_index(op.f('ix_processed_datasets_name'), table_name='processed_datasets')
    op.drop_index(op.f('ix_processed_datasets_creator_wallet_address'), table_name='processed_datasets')
    op.drop_table('processed_datasets')
    op.drop_index(op.f('ix_campaigns_title'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_onchain_campaign_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_premium'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_creator_wallet_address'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
