"""added a file type field on campaigns

Revision ID: 8fc52c9db64a
Revises: adf5f6445828
Create Date: 2025-05-22 00:03:08.622008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc52c9db64a'
down_revision: Union[str, None] = 'adf5f6445828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('file_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaigns_file_type'), 'campaigns', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_file_type'), table_name='campaigns')
    op.drop_column('campaigns', 'file_type')
    # ### end Alembic commands ###
